services:
  - type: web
    name: gemini-clone
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production