services:
  - type: web
    name: gemini-clone
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000